import Foundation
import XCTest
@testable import FlycutCore

final class SettingsTests: XCTestCase {
    func testLegacyDefaultsMatchUserFacingControls() {
        let settings = LegacySettingsMapper.map([:]).settings
        XCTAssertEqual(settings.recentCapacity, 40)
        XCTAssertEqual(settings.favoriteCapacity, 40)
        XCTAssertEqual(settings.menuPreviewCount, 10)
        XCTAssertEqual(settings.previewCharacterCount, 40)
        XCTAssertEqual(settings.hotkey, .init(keyCode: 9, modifierFlags: 1_179_648))
        XCTAssertEqual(settings.saveMode, .onQuit)
        XCTAssertTrue(settings.skipPasswordFields)
        XCTAssertTrue(settings.skipPasteboardTypes)
        XCTAssertEqual(settings.skippedPasteboardTypes, ["PasswordPboardType", "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"])
        XCTAssertFalse(settings.skipPasswordLengths)
        XCTAssertEqual(settings.skippedPasswordLengths, [12, 20, 32])
        XCTAssertFalse(settings.removeDuplicates)
        XCTAssertFalse(settings.openAtLogin)
        XCTAssertTrue(settings.saveForgottenFavorites)
        XCTAssertFalse(settings.syncSettingsViaICloud)
        XCTAssertFalse(settings.syncClippingsViaICloud)
    }

    func testTopLevelPreferencesTakePrecedenceOverNestedStoreFallback() {
        let result = LegacySettingsMapper.map([
            "rememberNum": 88, "displayLen": 75,
            "store": ["rememberNum": 12, "favoritesRememberNum": 13, "displayLen": 20, "displayNum": 7]
        ])
        XCTAssertEqual(result.settings.recentCapacity, 88)
        XCTAssertEqual(result.settings.favoriteCapacity, 13)
        XCTAssertEqual(result.settings.previewCharacterCount, 75)
        XCTAssertEqual(result.settings.menuPreviewCount, 7)
    }

    func testInvalidCapacitiesAndOutOfRangeAppearanceAreValidatedWithWarnings() {
        let result = LegacySettingsMapper.map([
            "rememberNum": 0, "favoritesRememberNum": -5, "displayNum": -1, "displayLen": 0,
            "bezelAlpha": 9, "bezelWidth": 20, "bezelHeight": 9000
        ])
        XCTAssertEqual(result.settings.recentCapacity, 40)
        XCTAssertEqual(result.settings.favoriteCapacity, 40)
        XCTAssertEqual(result.settings.menuPreviewCount, 10)
        XCTAssertEqual(result.settings.previewCharacterCount, 40)
        XCTAssertEqual(result.settings.bezelAlpha, 1)
        XCTAssertEqual(result.settings.bezelWidth, 200)
        XCTAssertEqual(result.settings.bezelHeight, 1200)
        XCTAssertFalse(result.warnings.isEmpty)
    }

    func testHotkeyDictionaryConvertsAndMalformedValueWarns() {
        let converted = LegacySettingsMapper.map(["ShortcutRecorder mainHotkey": ["keyCode": 42, "modifierFlags": 262_144]])
        XCTAssertEqual(converted.settings.hotkey, .init(keyCode: 42, modifierFlags: 262_144))
        let malformed = LegacySettingsMapper.map(["ShortcutRecorder mainHotkey": ["keyCode": -2]])
        XCTAssertEqual(malformed.settings.hotkey, .init(keyCode: 9, modifierFlags: 1_179_648))
        XCTAssertFalse(malformed.warnings.isEmpty)
    }

    func testAllThreeLegacySaveModesMapWithoutUpgradingNever() {
        XCTAssertEqual(LegacySettingsMapper.map(["savePreference": 0]).settings.saveMode, .never)
        XCTAssertEqual(LegacySettingsMapper.map(["savePreference": 1]).settings.saveMode, .onQuit)
        XCTAssertEqual(LegacySettingsMapper.map(["savePreference": 2]).settings.saveMode, .afterEachClip)
        XCTAssertEqual(LegacySettingsMapper.map(["savePreference": 3]).settings.saveMode, .onQuit)
        XCTAssertFalse(LegacySettingsMapper.map(["savePreference": 3]).warnings.isEmpty)
    }

    func testPrivacySkipListsAndControlsMap() {
        let result = LegacySettingsMapper.map([
            "skipPasswordFields": false, "skipPboardTypes": false,
            "skipPboardTypesList": "one, two,one", "skipPasswordLengths": true,
            "skipPasswordLengthsList": "12, 24, bad", "revealPasteboardTypes": true,
            "removeDuplicates": true, "pasteMovesToTop": true
        ])
        XCTAssertFalse(result.settings.skipPasswordFields)
        XCTAssertFalse(result.settings.skipPasteboardTypes)
        XCTAssertEqual(result.settings.skippedPasteboardTypes, ["one", "two", "one"])
        XCTAssertTrue(result.settings.skipPasswordLengths)
        XCTAssertEqual(result.settings.skippedPasswordLengths, [12, 24])
        XCTAssertTrue(result.settings.revealPasteboardTypes)
        XCTAssertTrue(result.settings.removeDuplicates)
        XCTAssertTrue(result.settings.pasteMovesToTop)
        XCTAssertFalse(result.warnings.isEmpty)
    }

    func testURLIconSourceAndMenuSettingsMap() {
        let url = URL(fileURLWithPath: "/tmp/Flycut Exports")
        let result = LegacySettingsMapper.map([
            "saveToLocation": url, "autoSaveToLocation": url.absoluteString,
            "menuIcon": 2, "displayClippingSource": false, "stickyBezel": true,
            "wraparoundBezel": true, "menuSelectionPastes": false, "popUpAnimation": false,
            "loadOnStartup": true, "saveForgottenClippings": true,
            "saveForgottenFavorites": true, "suppressAccessibilityAlert": true
        ])
        XCTAssertEqual(result.settings.saveToLocation, url)
        XCTAssertEqual(result.settings.autoSaveToLocation, url)
        XCTAssertEqual(result.settings.menuIcon, 2)
        XCTAssertFalse(result.settings.displayClippingSource)
        XCTAssertTrue(result.settings.stickyPalette)
        XCTAssertTrue(result.settings.wraparoundPalette)
        XCTAssertFalse(result.settings.menuSelectionPastes)
        XCTAssertFalse(result.settings.popUpAnimation)
        XCTAssertTrue(result.settings.openAtLogin)
        XCTAssertTrue(result.settings.saveForgottenClippings)
        XCTAssertTrue(result.settings.saveForgottenFavorites)
        XCTAssertTrue(result.settings.suppressAccessibilityAlert)
    }

    func testLegacyCloudFlagsCannotEnableUnprovisionedSync() {
        let result = LegacySettingsMapper.map(["syncSettingsViaICloud": true, "syncClippingsViaICloud": true])
        XCTAssertFalse(result.settings.syncSettingsViaICloud)
        XCTAssertFalse(result.settings.syncClippingsViaICloud)
        XCTAssertEqual(result.warnings.count, 2)
    }

    func testRemoteAndOverlongExportURLsAreRejected() {
        let result = LegacySettingsMapper.map([
            "saveToLocation": "https://example.com/export",
            "autoSaveToLocation": URL(fileURLWithPath: "/tmp/" + String(repeating: "a", count: 5000))
        ])
        XCTAssertNil(result.settings.saveToLocation)
        XCTAssertNil(result.settings.autoSaveToLocation)
        XCTAssertEqual(result.warnings.count, 2)
    }

    func testStorePersistsOnlyNamespacedKeysAndKeepsNeverMode() {
        let suite = "SettingsTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suite)!
        defer { defaults.removePersistentDomain(forName: suite) }
        defaults.set(123, forKey: "rememberNum")
        let store = SettingsStore(defaults: defaults)
        var settings = FlycutSettings()
        settings.saveMode = .never
        settings.recentCapacity = 72
        store.save(settings)
        XCTAssertEqual(defaults.integer(forKey: "rememberNum"), 123)
        XCTAssertEqual(defaults.integer(forKey: "v3.recentCapacity"), 72)
        XCTAssertEqual(store.load().saveMode, .never)
        XCTAssertEqual(store.load().recentCapacity, 72)
    }

    func testStoreClearsRemovedURLAndValidatesPersistedNumbers() {
        let suite = "SettingsTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suite)!
        defer { defaults.removePersistentDomain(forName: suite) }
        let store = SettingsStore(defaults: defaults)
        var settings = FlycutSettings()
        settings.saveToLocation = URL(fileURLWithPath: "/tmp/old")
        store.save(settings)
        XCTAssertNotNil(store.load().saveToLocation)
        settings.saveToLocation = nil
        store.save(settings)
        defaults.set(-7, forKey: "v3.recentCapacity")
        XCTAssertNil(store.load().saveToLocation)
        XCTAssertEqual(store.load().recentCapacity, 40)
    }
}
